export const Images = {
  indent: require('./indent.png'),
  outdent: require('./unindent.png'),
  bold: require('./type-bold.png'),
  italic: require('./type-italic.png'),
  underline: require('./type-underline.png'),
  strikethrough: require('./type-strikethrough.png'),
  h1: require('./type-h1.png'),
  h2: require('./type-h2.png'),
  h3: require('./type-h3.png'),
  h4: require('./type-h4.png'),
  h5: require('./type-h5.png'),
  h6: require('./type-h6.png'),
  orderedList: require('./list-ol.png'),
  bulletList: require('./list-ul.png'),
  checkList: require('./list-check.png'),
  undo: require('./undo.png'),
  redo: require('./redo.png'),
  link: require('./link.png'),
};
